CREATE TABLE trip_images (
   id INT AUTO_INCREMENT PRIMARY KEY,
   trip_id INT NOT NULL,
   image_url VARCHAR(500) NOT NULL,
   CONSTRAINT fk_trip_trip_image FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE CASCADE,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   deleted_at TIMESTAMP NULL DEFAULT NULL
);
