CREATE TABLE invitation_cooldowns (
   id INT AUTO_INCREMENT PRIMARY KEY,
   user_id_1 INT NOT NULL,
   user_id_2 INT NOT NULL,
   start_cooldown_millis BIGINT NOT NULL,
   cooldown_duration BIGINT NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   deleted_at TIMESTAMP NULL DEFAULT NULL,

   CONSTRAINT fk_user_1 FOREIGN KEY (user_id_1) REFERENCES users(id) ON DELETE CASCADE,
   CONSTRAINT fk_user_2 FOREIGN KEY (user_id_2) REFERENCES users(id) ON DELETE CASCADE
);