definitions:
  httpcommon.Error:
    properties:
      code:
        type: string
      field:
        type: string
      message:
        type: string
    type: object
  httpcommon.HttpResponse-any:
    properties:
      data: {}
      errors:
        items:
          $ref: '#/definitions/httpcommon.Error'
        type: array
      success:
        type: boolean
    type: object
  model.RegisterRequest:
    properties:
      email:
        maxLength: 255
        minLength: 10
        type: string
      name:
        maxLength: 255
        minLength: 5
        type: string
      password:
        maxLength: 255
        minLength: 8
        type: string
      phoneNumber:
        maxLength: 255
        minLength: 10
        type: string
    required:
    - email
    - name
    - password
    - phoneNumber
    type: object
  model.Student:
    properties:
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/students:
    get:
      description: Get all students
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Student'
            type: array
      summary: Get all students
      tags:
      - Student
  /auth/register:
    post:
      consumes:
      - application/json
      description: User register
      parameters:
      - description: Auth payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RegisterRequest'
      - description: 'Authorization: Bearer'
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpcommon.HttpResponse-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpcommon.HttpResponse-any'
      summary: Register user
      tags:
      - User
swagger: "2.0"
